Only have aria items on the actual input
cognitoforms/element pull request #57
Opened 2021-03-16 21:17 UTC by Nitrokitty

2021-03-17 12:45 UTC, tylertrotter commented
I'm thinking about this scenario:
![image](https://user-images.githubusercontent.com/4097146/111468590-1bba3200-86fc-11eb-816d-9ba0d9b16a69.png)

We never read "unread" or "read" which you might consider essential. It says "Mark your document checkbox unchecked" which kinda has the right meaning, but I wonder if should do something like this on the checkbox: `aria-label="Mark your document. Read"` so it says "Mark your document. Read checkbox unchecked." In other words `aria-label="ourLabel + '. ' + activeText"`

However, this is out of scope of the original problem so we shouldn't probably change it here. But let me know what you think.

2021-03-18 19:32 UTC, tylertrotter requested changes
Sorry, I don't know how github works. You have to "submit" your inline comments apparently.

2021-03-18 19:45 UTC, Nitrokitty commented on packages/switch/src/component.vue
> +        return this.name + ' ' + this.activeText;
done! I added it conditionally because if there's no label for some reason, it literally says "dot" haha

2021-03-18 19:45 UTC, Nitrokitty commented on packages/switch/src/component.vue
> +      @keydown.enter="switchValue()"
fixed!

2021-03-18 21:51 UTC, tylertrotter approved these changes
Beautiful!

2021-03-19 14:44 UTC, merged